export const E = {
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    SESSION_EXPIRED: 'SESSION_EXPIRED',

    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',

    VALIDATION_ERROR: 'VALIDATION_ERROR',
    MISSING_FIELD: 'MISSING_FIELD',
    INVALID_FORMAT: 'INVALID_FORMAT',

    WHATSAPP_NOT_CONNECTED: 'WHATSAPP_NOT_CONNECTED',
    CIRCUIT_OPEN: 'CIRCUIT_OPEN',
    QUEUE_RETRY_EXCEEDED: 'QUEUE_RETRY_EXCEEDED',
    BRIDGE_UNAVAILABLE: 'BRIDGE_UNAVAILABLE',
    INVALID_SIGNATURE: 'INVALID_SIGNATURE',
    REPLAY_DETECTED: 'REPLAY_DETECTED',

    INTERNAL_ERROR: 'INTERNAL_ERROR',
    DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export type ErrorCode = (typeof E)[keyof typeof E];
